import type {
  KeyboardBuild,
  PartsByType,
  SearchResult,
} from "@/types/keyboard";
import { magneticSwitches } from "@/data/switches";

export const initialParts: PartsByType = {
  keyboard_template: [
    {
      id: "template-neo65",
      type: "keyboard_template",
      name: "Neo65",
      brand: "Neo",
      layout: "65%",
      mount: "gasket",
      supportedPCBTypes: ["hotswap", "solder"],
      supportedPlateLayouts: ["65%"],
      supportedCaseLayouts: ["65%"],
      compatibleLayouts: ["65%"],
      materials: ["aluminum"],
      tags: ["hotswap", "gasket", "aluminum"],
    },
    {
      id: "template-mode75",
      type: "keyboard_template",
      name: "Mode Sonnet 75",
      brand: "Mode",
      layout: "75%",
      mount: "gasket",
      supportedPCBTypes: ["hotswap"],
      supportedPlateLayouts: ["75%"],
      supportedCaseLayouts: ["75%"],
      compatibleLayouts: ["75%"],
      materials: ["aluminum"],
      tags: ["75%", "gasket", "premium"],
    },
  ],
  keycap: [
    {
      id: "keycap-pbt-cream",
      type: "keycap",
      name: "PBT Cream Keycaps",
      brand: "MockKeys",
      material: "PBT",
      profile: "Cherry",
      materialStyle: "normal",
      colors: ["cream", "teal"],
      compatibleLayouts: ["60%", "65%", "75%", "TKL", "Alice"],
      tags: ["pbt", "cherry", "ansi"],
    },
  ],
  switch: [
    {
      id: "switch-oil-king",
      type: "switch",
      name: "Gateron Oil King",
      brand: "Gateron",
      switchType: "linear",
      actuationForce: 55,
      soundProfile: "thock",
      soundUrl: "/sounds/switch-linear-45.wav",
      compatiblePCBType: "mechanical",
      tags: ["linear", "factory-lubed", "deep"],
    },
    {
      id: "switch-brown-tactile",
      type: "switch",
      name: "Amber Tactile",
      brand: "MockSwitch",
      switchType: "tactile",
      actuationForce: 58,
      soundProfile: "creamy",
      soundUrl: "/sounds/switch-tactile-58.wav",
      compatiblePCBType: "mechanical",
      tags: ["tactile", "office"],
    },
    ...magneticSwitches,
  ],
  pcb: [
    {
      id: "pcb-neo65-hotswap",
      type: "pcb",
      name: "Neo65 Hotswap PCB",
      brand: "Neo",
      layout: "65%",
      pcbType: "mechanical",
      hotswap: true,
      rgb: true,
      compatibleLayouts: ["65%"],
      tags: ["hotswap", "rgb", "65%"],
    },
    {
      id: "pcb-75-hotswap",
      type: "pcb",
      name: "75% Hotswap RGB PCB",
      brand: "MockPCB",
      layout: "75%",
      pcbType: "mechanical",
      hotswap: true,
      rgb: true,
      compatibleLayouts: ["75%"],
      tags: ["hotswap", "rgb", "75%"],
    },
    {
      id: "pcb-magnetic-65",
      type: "pcb",
      name: "65% Magnetic PCB",
      brand: "MockHE",
      layout: "65%",
      pcbType: "magnetic",
      hotswap: true,
      rgb: true,
      compatibleLayouts: ["65%"],
      tags: ["magnetic", "hall_effect", "65%", "rgb"],
    },
  ],
  plate: [
    {
      id: "plate-fr4-65",
      type: "plate",
      name: "FR4 Plate 65%",
      brand: "MockPlate",
      layout: "65%",
      material: "FR4",
      compatibleLayouts: ["65%"],
      tags: ["fr4", "flex"],
    },
    {
      id: "plate-pc-75",
      type: "plate",
      name: "PC Plate 75%",
      brand: "MockPlate",
      layout: "75%",
      material: "PC",
      compatibleLayouts: ["75%"],
      tags: ["pc", "soft"],
    },
  ],
  case: [
    {
      id: "case-aluminum-65",
      type: "case",
      name: "Aluminum Case 65%",
      brand: "MockCase",
      layout: "65%",
      material: "aluminum",
      color: "#4B5563",
      compatibleLayouts: ["65%"],
      supportedDiffuserIds: ["diffuser-65-rgb"],
      tags: ["aluminum", "65%"],
    },
    {
      id: "case-aluminum-75",
      type: "case",
      name: "Aluminum Case 75%",
      brand: "MockCase",
      layout: "75%",
      material: "aluminum",
      color: "#374151",
      compatibleLayouts: ["75%"],
      supportedDiffuserIds: ["diffuser-75-rgb"],
      tags: ["aluminum", "75%"],
    },
  ],
  diffuser: [
    {
      id: "diffuser-65-rgb",
      type: "diffuser",
      name: "65% Ice Blue Diffuser",
      brand: "MockLight",
      color: "ice-blue",
      compatibleCaseLayouts: ["65%"],
      compatibleCaseMaterials: ["aluminum", "acrylic"],
      tags: ["rgb", "65%"],
    },
    {
      id: "diffuser-75-rgb",
      type: "diffuser",
      name: "75% Warm Diffuser",
      brand: "MockLight",
      color: "warm-white",
      compatibleCaseLayouts: ["75%"],
      compatibleCaseMaterials: ["aluminum", "acrylic"],
      tags: ["rgb", "75%"],
    },
  ],
  sound_pack: [
    {
      id: "sound-thock-linear",
      type: "sound_pack",
      name: "Thock Linear Pack",
      brand: "MockSound",
      soundProfile: "thock",
      compatibleSwitchTypes: ["linear", "tactile", "magnetic"],
      hasSpacebarAudio: true,
      audioUrl: "/sounds/sound-thock.wav",
      tags: ["thock", "linear"],
    },
    {
      id: "sound-clack-clicky",
      type: "sound_pack",
      name: "Clack Clicky Pack",
      brand: "MockSound",
      soundProfile: "clack",
      compatibleSwitchTypes: ["clicky", "tactile", "magnetic"],
      hasSpacebarAudio: false,
      audioUrl: "/sounds/sound-clack.wav",
      tags: ["clack", "clicky"],
    },
  ],
};

export const initialBuilds: KeyboardBuild[] = [];

export const mockSearchResults: SearchResult[] = [
  {
    title: "Neo65 Keyboard Kit",
    url: "https://example.com/neo65",
    image: "https://example.com/neo65.jpg",
    snippet: "65% gasket mount keyboard kit with hotswap PCB",
    source: "mock",
    confidence: 0.86,
    extractedPart: {
      type: "keyboard_template",
      name: "Neo65",
      brand: "Neo",
      layout: "65%",
      mount: "gasket",
      materials: ["aluminum"],
      compatibleLayouts: ["65%"],
      tags: ["hotswap", "gasket", "aluminum"],
    },
  },
  {
    title: "Gateron Oil King Linear Switch",
    url: "https://example.com/oil-king",
    image: "https://example.com/oil-king.jpg",
    snippet: "Factory lubed linear switch with a deep thock profile",
    source: "mock",
    confidence: 0.91,
    extractedPart: {
      type: "switch",
      name: "Gateron Oil King",
      brand: "Gateron",
      tags: ["linear", "factory-lubed", "deep"],
    },
  },
  {
    title: "PBT Keycaps Cherry Profile",
    url: "https://example.com/pbt-keycaps",
    image: "https://example.com/pbt-keycaps.jpg",
    snippet: "PBT keycap set covering 60%, 65%, 75%, TKL and Alice layouts",
    source: "mock",
    confidence: 0.78,
    extractedPart: {
      type: "keycap",
      name: "PBT Cream Keycaps",
      brand: "MockKeys",
      compatibleLayouts: ["60%", "65%", "75%", "TKL", "Alice"],
      tags: ["pbt", "cherry", "ansi"],
    },
  },
  {
    title: "FR4 Plate 65%",
    url: "https://example.com/fr4-65",
    image: "https://example.com/fr4-65.jpg",
    snippet: "FR4 plate for 65% gasket mount keyboard kits",
    source: "mock",
    confidence: 0.84,
    extractedPart: {
      type: "plate",
      name: "FR4 Plate 65%",
      brand: "MockPlate",
      layout: "65%",
      materials: ["FR4"],
      compatibleLayouts: ["65%"],
      tags: ["fr4", "65%", "flex"],
    },
  },
  {
    title: "75% Hotswap RGB PCB",
    url: "https://example.com/75-pcb",
    image: "https://example.com/75-pcb.jpg",
    snippet: "Hotswap PCB with RGB for 75% keyboard kits",
    source: "mock",
    confidence: 0.82,
    extractedPart: {
      type: "pcb",
      name: "75% Hotswap RGB PCB",
      brand: "MockPCB",
      layout: "75%",
      compatibleLayouts: ["75%"],
      tags: ["hotswap", "rgb", "75%"],
    },
  },
];
